
const texts = {
  noDestinations: 'No hay destinos en tu itinerario',
  destinationsTitle: '¡WanderLust!',
  pageTitle: 'Encuentra tu próximo destino',
  descriptionTitle: 'Descripción',
  priceTitle: 'Precio',
  activitiesTitle: 'Actividades',
  reviewsTitle: 'Opiniones',
  reviewsComment: 'Dejanos tu comentario...',
  reviewsPlaceholder: 'Comentario...',
  ratingTitle: 'Puntuación',
  newComment: 'Comentar',
  placeNotFound: 'Este lugar no pertenece a este planeta!',
  yourTripTitle: 'Tu Viaje',
  myTripTitle: 'Mi Viaje',
  addAsDestiantion: 'Agregar al viaje',
  signIn: 'Ingresar',
  signOut: 'Salir',
  add: 'Agregar',
  signInToAddDestination: 'Inicia sesión para agregar',
  delete: 'Borrar',
  up: 'Subir',
  down: 'Bajar',
  username: 'Usuario',
  password: 'Contraseña',
  comment: 'Comentario',
  find: 'Buscar',
  chooseAContinent: 'Elige un continente',
  places: 'Lugares',
  placeDetail: 'Detalle',
  added: 'Se agregó exitosamente!',
  error: 'Error',
  signInError: 'Usuario o contraseña incorrecta',
  addPhoto: 'Agregar foto',
  regions: 'Regiones'
};

export default texts;